export const FETCH_ALBUMS_COMPLETED = 'FETCH_ALBUMS_COMPLETED';
export const FETCH_ALBUMS_STARTED = 'FETCH_ALBUMS_STARTED';
export const FETCH_ALBUMS_FAILED = 'FETCH_ALBUMS_FAILED';

export const FETCH_SELECTED_ALBUM_COMPLETED = 'FETCH_SELECTED_ALBUM_COMPLETED';
export const FETCH_SELECTED_ALBUM_STARTED = 'FETCH_SELECTED_ALBUM_STARTED';
export const FETCH_SELECTED_ALBUM_FAILED = 'FETCH_SELECTED_ALBUM_FAILED';

export const FETCH_ALBUMS_BY_GENRE_STARTED = 'FETCH_ALBUMS_BY_GENRE_STARTED';
export const FETCH_ALBUMS_BY_GENRE_COMPLETED = 'FETCH_ALBUMS_BY_GENRE_COMPLETED';
export const FETCH_ALBUMS_BY_GENRE_FAILED = 'FETCH_ALBUMS_BY_GENRE_FAILED';
