/* eslint-disable prettier/prettier */
export const FETCH_ARTISTS_COMPLETED = 'FETCH_ARTISTS_COMPLETED';
export const FETCH_ARTISTS_STARTED = 'FETCH_ARTISTS_STARTED';
export const FETCH_ARTISTS_FAILED = 'FETCH_ARTISTS_FAILED';

export const FETCH_SELECTED_ARTIST_COMPLETED = 'FETCH_SELECTED_ARTIST_COMPLETED';
export const FETCH_SELECTED_ARTIST_STARTED = 'FETCH_SELECTED_ARTIST_STARTED';
export const FETCH_SELECTED_ARTIST_FAILED = 'FETCH_SELECTED_ARTIST_FAILED';

export const FETCH_ARTISTS_BY_GENRE_STARTED = 'FETCH_ARTISTS_BY_GENRE_STARTED';
export const FETCH_ARTISTS_BY_GENRE_COMPLETED = 'FETCH_ARTISTS_BY_GENRE_COMPLETED';
export const FETCH_ARTISTS_BY_GENRE_FAILED = 'FETCH_ARTISTS_BY_GENRE_FAILED';
