export const AUTHENTICATION_STARTED = 'AUTHENTICATION_STARTED';
export const AUTHENTICATION_COMPLETED = 'AUTHENTICATION_COMPLETED';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
export const AUTHENTICATION_IDENTITY_CLEARED = 'AUTHENTICATION_IDENTITY_CLEARED';

export const REGISTRATION_STARTED = 'REGISTRATION_STARTED';
export const REGISTRATION_SUCCEDED = 'REGISTRATION_SUCCEDED';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';

export const CHANGE_PASSWORD_STARTED = 'CHANGE_PASSWORD_STARTED';
export const CHANGE_PASSWORD_COMPLETED = 'CHANGE_PASSWORD_COMPLETED';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';
