/* eslint-disable prettier/prettier */
/* eslint-disable semi */
// eslint-disable-next-line prettier/prettier
export const ADD_FAVORITES_FAILED = 'ADD_FAVORITES_FAILED'
export const ADD_FAVORITES_STARTED = 'ADD_FAVORITES_STARTED'
export const ADD_FAVORITES_COMPLETED = 'ADD_FAVORITES_COMPLETED'

export const FETCH_FAVORITES_COMPLETED = 'FETCH_FAVORITES_COMPLETED'
export const FETCH_FAVORITES_STARTED = 'FETCH_FAVORITES_STARTED'
export const FETCH_FAVORITES_FAILED = 'FETCH_FAVORITES_FAILED'

export const DELETE_FAVORITES_COMPLETED = 'DELETE_FAVORITES_COMPLETED'
export const DELETE_FAVORITES_STARTED = 'DELETE_FAVORITES_STARTED'
export const DELETE_FAVORITES_FAILED = 'DELETE_FAVORITES_FAILED'
