export const SET_ROOT_NAVIGATOR_STARTED = 'SET_ROOT_NAVIGATOR_STARTED';
export const SET_ROOT_NAVIGATOR_FAILED = 'SET_ROOT_NAVIGATOR_SUCCEDED';
export const SET_ROOT_NAVIGATOR_SUCCEDED = 'SET_ROOT_NAVIGATOR_FAILED';