/* eslint-disable prettier/prettier */
/* eslint-disable semi */
// eslint-disable-next-line prettier/prettier
export const ADD_PLAYLISTS_fAILED = 'ADD_PLAYLISTS_fAILED'
export const ADD_PLAYLISTS_STARTED = 'ADD_PLAYLISTS_STARTED'
export const ADD_PLAYLISTS_COMPLETED = 'ADD_PLAYLISTS_COMPLETED'

export const FETCH_PLAYLISTS_COMPLETED = 'FETCH_PLAYLISTS_COMPLETED'
export const FETCH_PLAYLISTS_STARTED = 'FETCH_PLAYLISTS_STARTED'
export const FETCH_PLAYLISTS_FAILED = 'FETCH_PLAYLISTS_FAILED'

export const DELETE_PLAYLISTS_COMPLETED = 'DELETE_PLAYLISTS_COMPLETED'
export const DELETE_PLAYLISTS_STARTED = 'DELETE_PLAYLISTS_STARTED'
export const DELETE_PLAYLISTS_FAILED = 'DELETE_PLAYLISTS_FAILED'

export const ADD_TRACK_TO_PLAYLIST_STARTED = 'ADD_TRACK_TO_PLAYLIST_STARTED'
export const ADD_TRACK_TO_PLAYLIST_COMPLETED = 'ADD_TRACK_TO_PLAYLIST_COMPLETED'
export const ADD_TRACK_TO_PLAYLIST_FAILED = 'ADD_TRACK_TO_PLAYLIST_FAILED'
