/* eslint-disable prettier/prettier */
/* eslint-disable quotes */
export const FETCH_PROFILE_STARTED = "FETCH_PROFILE_STARTED";
export const FETCH_PROFILE_COMPLETED = "FETCH_PROFILE_COMPLETED";
export const FETCH_PROFILE_FAILED = "FETCH_PROFILE_FAILED";

export const UPDATE_PROFILE_STARTED = "UPDATE_PROFILE_STARTED";
export const UPDATE_PROFILE_COMPLETED = "UPDATE_PROFILE_COMPLETED";
export const UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED";
