export const FETCH_TRACKS_SUCCEDED = 'FETCH_TRACKS_SUCCEDED';
export const FETCH_TRACKS_STARTED = 'FETCH_TRACKS_STARTED';
export const FETCH_TRACKS_FAILED = 'FETCH_TRACKS_FAILED';

export const FETCH_TRACKS_BY_GENRE_SUCCEDED = 'FETCH_TRACKS_BY_GENRE_SUCCEDED';
export const FETCH_TRACKS_BY_GENRE_STARTED = 'FETCH_TRACKS_BY_GENRE_STARTED';
export const FETCH_TRACKS_BY_GENRE_FAILED = 'FETCH_TRACKS_FAILED';

export const FETCH_SELECTED_TRACK_SUCCEDED = 'FETCH_SELECTED_TRACK_SUCCEDED';
export const FETCH_SELECTED_TRACK_STARTED = 'FETCH_SELECTED_TRACK_STARTED';
export const FETCH_SELECTED_TRACK_FAILED = 'FETCH_SELECTED_TRACK_FAILED';
